$notinlist = "Processing path: C:\\TEMP\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi`nProcessing folder: \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi`nPost-processing files: ['Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv']`nPost-processing video files: ['Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv']`nProcessing failed for \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv: This show isn't in your list, you need to add it before post-processing an episode`nProblem(s) during processing, failed for the following files/folders: `nMissed file: \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode"
$foldernotexist = "Post-processing attempted but directory doesn't exist: C:\\TEMP\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOG"
$success = "Processing path: C:\\TEMP\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi`nProcessing folder: \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi`nPost-processing files: ['Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv']`nPost-processing video files: ['Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv']`nProcessing \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv`nShow information parsed from file name`nRetrieving episode object for Your Honor (US) S01E05`nThe episode file has a quality in it, using that: 4K UHD WEB-DL`nSnatch in history: False`nManually snatched: False`nInfo hash: None`nNZB: False`nCurrent quality: 4K UHD WEB-DL`nNew quality: 4K UHD WEB-DL`nProper: False`nThis episode is a priority download: True`nOld file: C:\\DATA\\TVSeries\\Your Honor (US)\\Season 01\\Your Honor (US) - S01E05 - [2160p WEB h265][KOGi].mkv`nNew file: \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv`nOld size: 5.58 GB`nNew size: 5.58 GB`nNew file is the same size.`nSetting to clean Kodi library as we are going to replace the file`nThis download is marked a priority download so I'm going to replace an existing file if I find one`nFound the following associated files for C:\\DATA\\TVSeries\\Your Honor (US)\\Season 01\\Your Honor (US) - S01E05 - [2160p WEB h265][KOGi].mkv: {'C:\\\\DATA\\\\TVSeries\\\\Your Honor (US)\\\\Season 01\\\\Your Honor (US) - S01E05 - [2160p WEB h265][KOGi].en.srt'}`nDeleting file: C:\\DATA\\TVSeries\\Your Honor (US)\\Season 01\\Your Honor (US) - S01E05 - [2160p WEB h265][KOGi].mkv`nDeleting file: C:\\DATA\\TVSeries\\Your Honor (US)\\Season 01\\Your Honor (US) - S01E05 - [2160p WEB h265][KOGi].en.srt`nFound release name Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi`nDestination folder for this episode: C:\\DATA\\TVSeries\\Your Honor (US)\\Season 01`nNo associated files were found for \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv`nNo associated files were found for \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv`nMoving file from \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv to C:\\DATA\\TVSeries\\Your Honor (US)\\Season 01\\Your Honor (US) - S01E05 - [2160p WEB h265][KOGi].mkv `nProcessing succeeded for \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi.mkv`nDeleted folder: \\\\HYPERV\\TEMP$\\Torrent\\PROCD\\TV\\Your.Honor.S01E05.HDR.2160p.WEB.h265-KOGi`nPost-processing completed."

foreach ($line in $success) {
    Write-Output $line
    switch -Regex ($line) {
        "directory doesn't exist" {
            $MedusaPP = 'FolderDoesNotExist'
        }
        "This show isn't in your list" {
            $MedusaPP = 'FolderDoesNotExist'
        }
        "Post-processing completed." {
            # Write-Output $line
        }
    }

}